services:
  postgres:
    image: postgres:16-alpine
    container_name: indexer-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: indexer_seo
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: indexer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U indexer -d indexer_seo"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-stack:
    image: redis/redis-stack:7.4.0-v8
    container_name: redis-stack
    ports:
      - "637:6379" # bind to localhost ONLY
      - "8001:8001" # Redis Insight | Open to see working details
    volumes:
      - redis_data:/data
    environment:
      REDIS_ARGS: >
        --requirepass strongpassword123
        --appendonly yes
        --protected-mode yes

  workers:
    build: .
    depends_on:
      - redis-stack
      - postgres
    env_file:
      - ./creds/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://indexer:indexer@postgres:5432/indexer_seo
    volumes:
      - logs:/app/logs # container path

    restart: unless-stopped

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/quick-seo/logs # host path
      o: bind

  redis_data:
  postgres_data:
