services:
  redis-stack:
    image: redis/redis-stack:7.4.0-v8
    container_name: redis-stack
    ports:
      - "6380:6379" # bind to localhost ONLY
      - "8001:8001" # Redis Insight | Open to see working details
    volumes:
      - redis_data:/data
    environment:
      REDIS_ARGS: >
        --requirepass strongpassword123
        --appendonly yes
        --protected-mode yes

  workers:
    build: .
    depends_on:
      - redis-stack
    volumes:
      - logs:/app/logs # container path

    restart: unless-stopped

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/quick-seo/logs # host path
      o: bind

  redis_data:
